# Generated by Django 2.0.2 on 2018-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=280)),
                ('deadline', models.CharField(default='', max_length=24)),
            ],
        ),
    ]
