# Generated by Django 2.0.2 on 2018-05-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheToDos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='percent',
            field=models.IntegerField(default='0'),
        ),
    ]
